CREATE TABLE  houses (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(50) NOT NULL,
	image_name VARCHAR(255),
	postal_code VARCHAR(50) NOT NULL,
	adress VARCHAR(255) NOT NULL,
	description VARCHAR(255) NOT NULL,
	price INT NOT NULL,	
	business_hours INT NOT NULL,
	phone_number VARCHAR(50) NOT NULL,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
 );
